### ISSUE TITLE
app_id not found. You may be missing a Content-Type: application/json header

### ISSUE THREAD

**Issue by tamoyal** [tbalthazar/onesignal-ruby#11]
I can't figure out how to get past this error so will prob resort to hitting the API directly. You may want to update your docs to reflect the language on the OneSignal keys & ids section. They use `OneSignal App ID` and `REST API Key`. I would do it for you but honestly I'm not sure which is which with your lib.

**Comment by tamoyal** [comment]
Steps to reproduce:
```
# found in your app settings
OneSignal::OneSignal.api_key = ENV['ONE_SIGNAL_REST_KEY']
# try a call
OneSignal::Player.all
```

**Comment by tbalthazar** [comment]
Hi @tamoyal,

For clarification, `REST API Key` is equal to `OneSignal::OneSignal.api_key`.

The error message you get is `app_id not found. You may be missing a Content-Type: application/json header.`, that's because you didn't provide an `app_id`.

As explained [here](https://github.com/tbalthazar/onesignal-ruby#players), the `all` method takes a `params` argument.

And in the OneSignal doc, you can see that to view devices, [you need to specify](https://documentation.onesignal.com/reference#view-devices) the `app_id`.

So :
```ruby
OneSignal::Player.all
```

should be :
```ruby
OneSignal::Player.all(params: {app_id: 'your_app_id'})
```
The `app_id` can be found in the _App Settings_ of your app in the OneSignal dashboard.
