### ISSUE TITLE
Why Ruby 2.2 is the minimum dependency?

### ISSUE THREAD

**Issue by mohitjain** [tbalthazar/onesignal-ruby#6]
Hey,

I am not able to find out anything which justifies ruby 2.2 dependency? Can you please tell me why you choose 2.2 instead of 2 or 1.9.3. I am looking for 2.1.5 :)

**Comment by tbalthazar** [comment]
Hi,

Thanks for your remark on this. That's true that the requirement is too high.
I lowered it to ruby 2.1. I cannot go lower than that for now because ruby 2.1 requires default values for keyword arguments, as explained here: http://blog.rkh.im/ruby-2.1.

I've pushed version 0.0.14 which only requires ruby 2.1.0.

Best,
Thomas.

**Comment by mohitjain** [comment]
Thanks a lot :)
